spring:
  application:
    name: notification-service
  rabbitmq:
    template:
      reply-timeout: 15000
      retry:
        enabled: false
    host: 192.168.99.100

server:
  port: 9104

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

logging:
  level:
    com:
      netflix:
        eureka: INFO
        discovery: INFO