server:
  port: 8762

spring:
  application:
    name: zuul-server


zuul:
  ignoredServices: '*'
  routes:
    authService:
      path: /auth/**
      serviceId: auth-service
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie
    loginService:
      path: /users/**
      serviceId: login-service
      stripPrefix: false
    ui:
      path: /**
      url: http://localhost:4200



logging:
  level:
    org:
      springframework:
        cloud:
          netflix: INFO


